// Generated by dts-bundle v0.3.0

declare module 'cu-rest-api' {
    class CuRestLibrary {
        login(email: string, password: string): Promise<{}>;
        fetchCharacters(loginToken: LoginToken): Promise<{}>;
        fetchAbilities(characterID: CharacterID, loginToken: LoginToken): Promise<{}>;
    }
    export default CuRestLibrary;
}

